version: '3'
services:
  ranger-db:
    build:
      context: .
      dockerfile: Dockerfile.ranger-postgres
    image: ranger-postgres
    container_name: ranger-postgres
    hostname: ranger-db.example.com
    networks:
      - ranger
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -q']
      interval: 10s
      timeout: 2s
      retries: 30

networks:
  ranger:
    name: rangernw
